import { NavigatorItem } from "@/types";
import { MdOutlineComputer } from "react-icons/md";

export const tempNavigatorItems: NavigatorItem[] = [
  {
    title: "Categories",
    value: 1,
    icon: "/icons/categories.png",
    route: "/categories",
  },
  {
    title: "Questions",
    value: 2,
    icon: "/icons/question.png",
    route: "/questions",
  },
  {
    title: "Community",
    value: 3,
    icon: "/icons/people.png",
    route: "/community",
  },
  { title: "Jobs", value: 4, icon: "/icons/job.png", route: "/jobs" },
  { title: "Tags", value: 5, icon: "/icons/tag.png", route: "/tags" },
  { title: "Badges", value: 6, icon: "/icons/badges.png", route: "/badges" },
  {
    title: "Unanswered",
    value: 7,
    icon: "/icons/unanswered.png",
    route: "/unanswered",
  },
];

export const tempLatestQuestions = [
  {
    id: 1,
    title: "How to make a website?",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "John Doe",
    category: "Computer",
  },
  {
    id: 2,
    title:
      "Why my wisedom teeth are paining? What should I do? and this is a very long question",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "visual basic", "javascript"],
    owner: "Haj Kazem",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
  {
    id: 4,
    title:
      "Where to find the best coffee in town? lorem ipsum dolor sit amet consectetur adipisicing elit lorem ipsum dolor sit amet consectetur adipisicing elit",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "typescript", "java"],
    owner: "Bagher Italy",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
];

export const popularCatgories = [
  {
    id: 1,
    name: "Computer",
    questions: 100,
    followers: 200,
  },
  {
    id: 2,
    name: "health & fitness",
    questions: 100,
    followers: 200,
  },
  {
    id: 3,
    name: "Science",
    questions: 100,
    followers: 200,
  },
  {
    id: 4,
    name: "Engineering",
    questions: 100,
    followers: 200,
  },
  {
    id: 5,
    name: "Politics",
    questions: 100,
    followers: 200,
  },
  {
    id: 7,
    name: "Technology",
    questions: 100,
    followers: 200,
  },
];

export const tempCatgories = [
  {
    id: 1,
    name: "Computer",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 2,
    name: "health & fitness",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 3,
    name: "Science",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 4,
    name: "Engineering",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 5,
    name: "Politics",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 6,
    name: "Religion",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 7,
    name: "Technology",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 8,
    name: "Business",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 9,
    name: "Economy",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 10,
    name: "Education",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 11,
    name: "History",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 12,
    name: "Art",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 13,
    name: "Music",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 14,
    name: "Sport",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 15,
    name: "Cinema",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 16,
    name: "Literature",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 17,
    name: "Philosophy",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 18,
    name: "Psychology",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 19,
    name: "Sociology",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 20,
    name: "Geography",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 21,
    name: "Mathematics",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 22,
    name: "Physics",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 23,
    name: "Chemistry",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 24,
    name: "Biology",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
];

export const tempPopularTags = [
  {
    id: 1,
    name: "html",
    questions: 100,
    followers: 200,
  },
  {
    id: 2,
    name: "css",
    questions: 100,
    followers: 200,
  },
  {
    id: 3,
    name: "javascript",
    questions: 100,
    followers: 200,
  },
  {
    id: 4,
    name: "react",
    questions: 100,
    followers: 200,
  },
  {
    id: 5,
    name: "angular",
    questions: 100,
    followers: 200,
  },
  {
    id: 6,
    name: "vue",
    questions: 100,
    followers: 200,
  },
  {
    id: 7,
    name: "node",
    questions: 100,
    followers: 200,
  },
  {
    id: 8,
    name: "express",
    questions: 100,
    followers: 200,
  },
  {
    id: 9,
    name: "mongodb",
    questions: 100,
    followers: 200,
  },
  {
    id: 10,
    name: "sql",
    questions: 100,
    followers: 200,
  },
  {
    id: 11,
    name: "mysql",
    questions: 100,
    followers: 200,
  },
  {
    id: 12,
    name: "python",
    questions: 100,
    followers: 200,
  },
  {
    id: 13,
    name: "java",
    questions: 100,
    followers: 200,
  },
];

export const users = [
  {
    id: 1,
    name: "John Doe",
    questions: 100,
    answers: 200,
    userName: "john_doe",
    avatar: "icons/avatar-man.svg",
    bio: "I am a web developer",
    currentLevel: "Beginner",
    nextLevel: "Intermediate",
    currentProgress: 60,
    rank: 15,
  },
  {
    id: 2,
    name: "Jane Smith",
    questions: 80,
    answers: 150,
    userName: "jane_smith",
    avatar: "icons/avatar-man.svg",
    bio: "I love coding",
    currentLevel: "Intermediate",
    nextLevel: "Advanced",
    currentProgress: 45,
    rank: 10,
  },
  {
    id: 3,
    name: "Alex Brown",
    questions: 120,
    answers: 300,
    userName: "alex_brown",
    avatar: "icons/avatar-man.svg",
    bio: "Full stack developer",
    currentLevel: "Beginner",
    nextLevel: "Intermediate",
    currentProgress: 30,
    rank: 25,
  },
  {
    id: 4,
    name: "Emily Davis",
    questions: 60,
    answers: 90,
    userName: "emily_davis",
    avatar: "icons/avatar-man.svg",
    bio: "Frontend engineer",
    currentLevel: "Intermediate",
    nextLevel: "Advanced",
    currentProgress: 55,
    rank: 18,
  },
  {
    id: 5,
    name: "Michael Lee",
    questions: 150,
    answers: 200,
    userName: "michael_lee",
    avatar: "icons/avatar-man.svg",
    bio: "Backend specialist",
    currentLevel: "Advanced",
    nextLevel: "Expert",
    currentProgress: 70,
    rank: 5,
  },
  {
    id: 6,
    name: "Sarah Wilson",
    questions: 30,
    answers: 50,
    userName: "sarah_wilson",
    avatar: "icons/avatar-man.svg",
    bio: "Mobile app developer",
    currentLevel: "Beginner",
    nextLevel: "Intermediate",
    currentProgress: 20,
    rank: 30,
  },
  {
    id: 7,
    name: "David Clark",
    questions: 90,
    answers: 110,
    userName: "david_clark",
    avatar: "icons/avatar-man.svg",
    bio: "Software engineer",
    currentLevel: "Intermediate",
    nextLevel: "Advanced",
    currentProgress: 50,
    rank: 12,
  },
  {
    id: 8,
    name: "Sophia Martinez",
    questions: 40,
    answers: 70,
    userName: "sophia_martinez",
    avatar: "icons/avatar-man.svg",
    bio: "UX/UI designer",
    currentLevel: "Beginner",
    nextLevel: "Intermediate",
    currentProgress: 35,
    rank: 28,
  },
  {
    id: 9,
    name: "James Garcia",
    questions: 110,
    answers: 170,
    userName: "james_garcia",
    avatar: "icons/avatar-man.svg",
    bio: "Data scientist",
    currentLevel: "Advanced",
    nextLevel: "Expert",
    currentProgress: 65,
    rank: 8,
  },
  {
    id: 10,
    name: "Linda Rodriguez",
    questions: 95,
    answers: 120,
    userName: "linda_rodriguez",
    avatar: "icons/avatar-man.svg",
    bio: "DevOps engineer",
    currentLevel: "Intermediate",
    nextLevel: "Advanced",
    currentProgress: 40,
    rank: 20,
  },
  {
    id: 11,
    name: "Chris Johnson",
    questions: 85,
    answers: 130,
    userName: "chris_johnson",
    avatar: "icons/avatar-man.svg",
    bio: "Cloud architect",
    currentLevel: "Advanced",
    nextLevel: "Expert",
    currentProgress: 75,
    rank: 6,
  },
  {
    id: 12,
    name: "Patricia King",
    questions: 50,
    answers: 65,
    userName: "patricia_king",
    avatar: "icons/avatar-man.svg",
    bio: "Machine learning enthusiast",
    currentLevel: "Beginner",
    nextLevel: "Intermediate",
    currentProgress: 25,
    rank: 22,
  },
  {
    id: 13,
    name: "Robert Wright",
    questions: 70,
    answers: 85,
    userName: "robert_wright",
    avatar: "icons/avatar-man.svg",
    bio: "Cybersecurity expert",
    currentLevel: "Intermediate",
    nextLevel: "Advanced",
    currentProgress: 60,
    rank: 14,
  },
  {
    id: 14,
    name: "Laura Green",
    questions: 130,
    answers: 220,
    userName: "laura_green",
    avatar: "icons/avatar-man.svg",
    bio: "AI researcher",
    currentLevel: "Advanced",
    nextLevel: "Expert",
    currentProgress: 85,
    rank: 4,
  },
  {
    id: 15,
    name: "Daniel Adams",
    questions: 20,
    answers: 30,
    userName: "daniel_adams",
    avatar: "icons/avatar-man.svg",
    bio: "Junior software developer",
    currentLevel: "Beginner",
    nextLevel: "Intermediate",
    currentProgress: 10,
    rank: 35,
  },
  {
    id: 16,
    name: "Lisa Baker",
    questions: 100,
    answers: 180,
    userName: "lisa_baker",
    avatar: "icons/avatar-man.svg",
    bio: "Mobile app enthusiast",
    currentLevel: "Intermediate",
    nextLevel: "Advanced",
    currentProgress: 48,
    rank: 11,
  },
  {
    id: 17,
    name: "Steven Turner",
    questions: 140,
    answers: 230,
    userName: "steven_turner",
    avatar: "icons/avatar-man.svg",
    bio: "Blockchain developer",
    currentLevel: "Advanced",
    nextLevel: "Expert",
    currentProgress: 90,
    rank: 3,
  },
  {
    id: 18,
    name: "Kimberly Harris",
    questions: 35,
    answers: 55,
    userName: "kimberly_harris",
    avatar: "icons/avatar-man.svg",
    bio: "Game developer",
    currentLevel: "Beginner",
    nextLevel: "Intermediate",
    currentProgress: 28,
    rank: 27,
  },
  {
    id: 19,
    name: "Paul Scott",
    questions: 75,
    answers: 105,
    userName: "paul_scott",
    avatar: "icons/avatar-man.svg",
    bio: "Cloud security engineer",
    currentLevel: "Intermediate",
    nextLevel: "Advanced",
    currentProgress: 52,
    rank: 17,
  },
  {
    id: 20,
    name: "Karen Evans",
    questions: 55,
    answers: 75,
    userName: "karen_evans",
    avatar: "icons/avatar-man.svg",
    bio: "Database administrator",
    currentLevel: "Intermediate",
    nextLevel: "Advanced",
    currentProgress: 42,
    rank: 19,
  },
];

export const tempTags = [
  {
    id: 1,
    name: "html",
    questions: 100,
    followers: 200,
    description:
      "A markup language for creating web pages and web applications.",
  },
  {
    id: 2,
    name: "css",
    questions: 100,
    followers: 200,
    description:
      "A style sheet language used for describing the look and formatting of a website.",
  },
  {
    id: 3,
    name: "javascript",
    questions: 100,
    followers: 200,
    description:
      "A programming language that enables interactive web development.",
  },
  {
    id: 4,
    name: "react",
    questions: 100,
    followers: 200,
    description:
      "A JavaScript library for building user interfaces, maintained by Facebook.",
  },
  {
    id: 5,
    name: "angular",
    questions: 100,
    followers: 200,
    description:
      "A TypeScript-based framework for building web applications, developed by Google.",
  },
  {
    id: 6,
    name: "vue",
    questions: 100,
    followers: 200,
    description:
      "A progressive JavaScript framework for building user interfaces.",
  },
  {
    id: 7,
    name: "node",
    questions: 100,
    followers: 200,
    description:
      "A runtime environment that lets you run JavaScript code outside the browser.",
  },
  {
    id: 8,
    name: "express",
    questions: 100,
    followers: 200,
    description:
      "A web application framework for Node.js, designed for building web applications and APIs.",
  },
  {
    id: 9,
    name: "mongodb",
    questions: 100,
    followers: 200,
    description: "A NoSQL database that stores data in JSON-like documents.",
  },
  {
    id: 10,
    name: "sql",
    questions: 100,
    followers: 200,
    description:
      "A domain-specific language for managing and manipulating relational databases.",
  },
  {
    id: 11,
    name: "mysql",
    questions: 100,
    followers: 200,
    description:
      "An open-source relational database management system based on SQL.",
  },
  {
    id: 12,
    name: "python",
    questions: 100,
    followers: 200,
    description:
      "A high-level programming language known for its readability and versatility.",
  },
  {
    id: 13,
    name: "java",
    questions: 100,
    followers: 200,
    description:
      "A popular programming language and platform widely used for enterprise applications.",
  },
  {
    id: 14,
    name: "csharp",
    questions: 80,
    followers: 150,
    description:
      "A programming language developed by Microsoft for building a variety of applications.",
  },
  {
    id: 15,
    name: "php",
    questions: 90,
    followers: 140,
    description:
      "A popular general-purpose scripting language especially suited to web development.",
  },
  {
    id: 16,
    name: "ruby",
    questions: 70,
    followers: 120,
    description:
      "A dynamic, open-source programming language with a focus on simplicity and productivity.",
  },
  {
    id: 17,
    name: "graphql",
    questions: 60,
    followers: 130,
    description:
      "A query language for APIs and a runtime for executing those queries.",
  },
  {
    id: 18,
    name: "docker",
    questions: 110,
    followers: 220,
    description:
      "A tool designed to make it easier to create, deploy, and run applications using containers.",
  },
  {
    id: 19,
    name: "kubernetes",
    questions: 75,
    followers: 180,
    description:
      "An open-source platform for automating the deployment, scaling, and operations of containers.",
  },
  {
    id: 20,
    name: "aws",
    questions: 120,
    followers: 250,
    description: "A suite of cloud computing services provided by Amazon.",
  },
  {
    id: 21,
    name: "linux",
    questions: 100,
    followers: 230,
    description:
      "An open-source operating system widely used for servers and development environments.",
  },
];
