import { NavigatorItem } from "@/types";
import { MdOutlineComputer } from "react-icons/md";

export const tempNavigatorItems: NavigatorItem[] = [
  {
    title: "Categories",
    value: 1,
    icon: "/icons/categories.png",
    route: "/categories",
  },
  {
    title: "Questions",
    value: 2,
    icon: "/icons/question.png",
    route: "/questions",
  },
  {
    title: "Community",
    value: 3,
    icon: "/icons/people.png",
    route: "/community",
  },
  { title: "Jobs", value: 4, icon: "/icons/job.png", route: "/jobs" },
  { title: "Tags", value: 5, icon: "/icons/tag.png", route: "/tags" },
  { title: "Badges", value: 6, icon: "/icons/badges.png", route: "/badges" },
  {
    title: "Unanswered",
    value: 7,
    icon: "/icons/unanswered.png",
    route: "/unanswered",
  },
];

export const tempLatestQuestions = [
  {
    id: 1,
    title: "How to make a website?",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "John Doe",
    category: "Computer",
  },
  {
    id: 2,
    title:
      "Why my wisedom teeth are paining? What should I do? and this is a very long question",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "visual basic", "javascript"],
    owner: "Haj Kazem",
    category: "Computer",
  },
  {
    id: 3,
    title:
      "I need a new car, which one should I buy? so this is a very long question and it can be even longer than this",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "css", "javascript"],
    owner: "Ali Reza",
    category: "Computer",
  },
  {
    id: 4,
    title:
      "Where to find the best coffee in town? lorem ipsum dolor sit amet consectetur adipisicing elit lorem ipsum dolor sit amet consectetur adipisicing elit",
    votes: 10,
    answers: 5,
    views: 100,
    tags: ["html", "typescript", "java"],
    owner: "Bagher Italy",
    category: "Computer",
  },
];

export const popularCatgories = [
  {
    id: 1,
    name: "Computer",
    questions: 100,
    followers: 200,
  },
  {
    id: 2,
    name: "health & fitness",
    questions: 100,
    followers: 200,
  },
  {
    id: 3,
    name: "Science",
    questions: 100,
    followers: 200,
  },
  {
    id: 4,
    name: "Engineering",
    questions: 100,
    followers: 200,
  },
  {
    id: 5,
    name: "Politics",
    questions: 100,
    followers: 200,
  },
  {
    id: 7,
    name: "Technology",
    questions: 100,
    followers: 200,
  },
];

export const tempCatgories = [
  {
    id: 1,
    name: "Computer",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 2,
    name: "health & fitness",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 3,
    name: "Science",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 4,
    name: "Engineering",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 5,
    name: "Politics",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 6,
    name: "Religion",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 7,
    name: "Technology",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 8,
    name: "Business",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 9,
    name: "Economy",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 10,
    name: "Education",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 11,
    name: "History",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 12,
    name: "Art",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 13,
    name: "Music",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 14,
    name: "Sport",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 15,
    name: "Cinema",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 16,
    name: "Literature",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 17,
    name: "Philosophy",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 18,
    name: "Psychology",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 19,
    name: "Sociology",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 20,
    name: "Geography",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 21,
    name: "Mathematics",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 22,
    name: "Physics",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 23,
    name: "Chemistry",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
  {
    id: 24,
    name: "Biology",
    questions: 100,
    followers: 200,
    icon: <MdOutlineComputer />,
  },
];

export const tempPopularTags = [
  {
    id: 1,
    name: "html",
    questions: 100,
    followers: 200,
  },
  {
    id: 2,
    name: "css",
    questions: 100,
    followers: 200,
  },
  {
    id: 3,
    name: "javascript",
    questions: 100,
    followers: 200,
  },
  {
    id: 4,
    name: "react",
    questions: 100,
    followers: 200,
  },
  {
    id: 5,
    name: "angular",
    questions: 100,
    followers: 200,
  },
  {
    id: 6,
    name: "vue",
    questions: 100,
    followers: 200,
  },
  {
    id: 7,
    name: "node",
    questions: 100,
    followers: 200,
  },
  {
    id: 8,
    name: "express",
    questions: 100,
    followers: 200,
  },
  {
    id: 9,
    name: "mongodb",
    questions: 100,
    followers: 200,
  },
  {
    id: 10,
    name: "sql",
    questions: 100,
    followers: 200,
  },
  {
    id: 11,
    name: "mysql",
    questions: 100,
    followers: 200,
  },
  {
    id: 12,
    name: "python",
    questions: 100,
    followers: 200,
  },
  {
    id: 13,
    name: "java",
    questions: 100,
    followers: 200,
  },
];
